Description: Create an IAM User, IAM Keypair associated with it and store it in secrets manager
Resources:
  User:
    Type: AWS::IAM::User
  Key:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref User
      Status: Active
  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      SecretString: !Sub
        - '{"username":"${AccessKey}","password":"${SecretKey}"}'
        - AccessKey: !Ref Key
          SecretKey: !GetAtt Key.SecretAccessKey
