Parameters:
  OrganizationId:
    Type: String
    Description: The id of the organization
  OrganizationManagementAccountId:
    Type: String
    Description: The account id of the organization account

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "tag-policy-report-bucket-${AWS::AccountId}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
          - Sid: TagPolicyACL
            Effect: Allow
            Principal:
              Service:
              - tagpolicies.tag.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !GetAtt Bucket.Arn
            Condition:
              StringLike:
                aws:SourceAccount: !Ref OrganizationManagementAccountId
                aws:SourceArn: !Sub arn:aws:tag:us-east-1:${OrganizationManagementAccountId}:*
          - Sid: TagPolicyBucketDelivery
            Effect: Allow
            Principal:
              Service:
              - tagpolicies.tag.amazonaws.com
            Action:
            - s3:PutObject
            - s3:PutObjectAcl
            Resource: !Sub arn:aws:s3:::${Bucket}/AwsTagPolicies/${OrganizationId}/*
            Condition:
              StringLike:
                aws:SourceAccount: !Ref OrganizationManagementAccountId
                aws:SourceArn: !Sub arn:aws:tag:us-east-1:${OrganizationManagementAccountId}:*

Outputs:
  BucketName:
    Description: The name of the S3 bucket
    Value: !Ref Bucket
