
Parameters:
  BucketName:
    Type: String
    Default: example-s3-to-sqs-bucket
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
Resources:
  Queue:
    Type: AWS::SQS::Queue
  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Id: SQSPolicy
        Statement:
        - Sid: SQSEventPolicy
          Effect: Allow
          Principal:
            Service: s3.amazonaws.com
          Action: sqs:SendMessage
          Resource: !GetAtt Queue.Arn
          Condition:
            ArnLike:
              aws:SourceArn: !Sub arn:aws:s3:::${BucketName}-${AWS::AccountId}
      Queues:
        - !Ref Queue
  Bucket:
    Type: AWS::S3::Bucket
    DependsOn:
      - QueuePolicy
    Properties:
      BucketName: !Sub ${BucketName}-${AWS::AccountId}
      NotificationConfiguration:
        QueueConfigurations:
          - Queue: !GetAtt Queue.Arn
            Event: s3:ObjectCreated:*
