Description: A CloudFormation script to create CloudWatch Alarms for monitor SES bounce and complaint rates

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: SES Bounce and Complaint Alarm
      TopicName: SESBounceAndComplaintAlarm

  SESBounceAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: SES BounceRate Alarm
      Namespace: AWS/SES
      MetricName: Reputation.BounceRate
      Statistic: Maximum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 0.025
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref SNSTopic

  SESComplaintAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: SES ComplaintRate Alarm
      Namespace: AWS/SES
      MetricName: Reputation.ComplaintRate
      Statistic: Maximum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 0.0005
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref SNSTopic

