Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC Id for ASG instances
  SubnetIds:
    Type: CommaDelimitedList
    Description: Comma separated list of subnet ids for ASG instances
  AllowedCidr:
    Type: String
    Description: CIDR of allowed ssh connections
  LatestAmiIdx86:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  LatestAmiIdArm:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-arm64-gp2'
  KeyName:
    Type: String
    Description: SSH key pair name

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AllowedCidr

  LaunchTemplatex86:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        KeyName: dmichael
        ImageId: !Ref LatestAmiIdx86
        SecurityGroupIds:
          - !Ref SecurityGroup

  LaunchTemplatexArm64:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        KeyName: !Ref KeyName
        ImageId: !Ref LatestAmiIdArm
        SecurityGroupIds:
          - !Ref SecurityGroup

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MaxSize: "8"
      MinSize: "1"
      DesiredCapacity: "3"
      CapacityRebalance: true
      VPCZoneIdentifier: !Ref SubnetIds
      MixedInstancesPolicy:
        InstancesDistribution:
          OnDemandBaseCapacity: 1
          SpotAllocationStrategy: lowest-price
          OnDemandPercentageAboveBaseCapacity: 10
        LaunchTemplate:
          LaunchTemplateSpecification:
            Version: !GetAtt LaunchTemplatex86.LatestVersionNumber
            LaunchTemplateId: !Ref LaunchTemplatex86
          Overrides:
            - InstanceType: t3a.nano
            - InstanceType: t3a.micro
            - InstanceType: t3a.small
            - InstanceType: t3a.medium
            - InstanceType: t3.nano
            - InstanceType: t3.micro
            - InstanceType: t3.small
            - InstanceType: t3.medium
            - InstanceType: t2.nano
            - InstanceType: t2.micro
            - InstanceType: t2.small
            - InstanceType: t2.medium
            - InstanceType: t4g.nano
              LaunchTemplateSpecification:
                LaunchTemplateId: !Ref LaunchTemplatexArm64
                Version: !GetAtt LaunchTemplatexArm64.LatestVersionNumber
            - InstanceType: t4g.micro
              LaunchTemplateSpecification:
                LaunchTemplateId: !Ref LaunchTemplatexArm64
                Version: !GetAtt LaunchTemplatexArm64.LatestVersionNumber
            - InstanceType: t4g.small
              LaunchTemplateSpecification:
                LaunchTemplateId: !Ref LaunchTemplatexArm64
                Version: !GetAtt LaunchTemplatexArm64.LatestVersionNumber
            - InstanceType: t4g.medium
              LaunchTemplateSpecification:
                LaunchTemplateId: !Ref LaunchTemplatexArm64
                Version: !GetAtt LaunchTemplatexArm64.LatestVersionNumber
