Resources:
  S3ReplicationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
  S3ReplicationPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetReplicationConfiguration
              - s3:ListBucket
              - s3:GetObject*
            Effect: Allow
            Resource:
              - !GetAtt SrcBucket.Arn
              - !Sub ${SrcBucket.Arn}/*
          - Action:
              - s3:ReplicateObject
              - s3:ReplicateDelete
            Effect: Allow
            Resource:
              - !GetAtt DestBucket.Arn
              - !Sub ${DestBucket.Arn}/*
      PolicyName: S3ObjectReplicationPolicy
      Roles:
        - !Ref S3ReplicationRole

  DestBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  SrcBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      ReplicationConfiguration:
        Role: !GetAtt S3ReplicationRole.Arn
        Rules:
          - Id: TestReplication
            Destination:
              Bucket: !GetAtt DestBucket.Arn
              ReplicationTime:
                Status: Enabled
                Time:
                  Minutes: 15
              Metrics:
                EventThreshold:
                  Minutes: 15
                Status: Enabled
            Filter:
              TagFilter:
                Key: Test
                Value: "True"
            DeleteMarkerReplication:
              Status: Disabled
            Status: Enabled
            Priority: 0
