name: Lint CloudFormation Templates

on: [push]

jobs:
  cloudformation-linter:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: cfn-lint
      uses: docker://ghcr.io/scottbrenner/cfn-lint-action:master
      with:
        args: "**/*.yaml"
